## What is a Jupyter Notebook?

A **Jupyter notebook** is an interactive document that mixes **explanatory text** (like this) with **live code** and its results. You write and run code in small chunks called *cells*, and the output appears directly below each cell. A notebook is saved as a file with the suffix `.ipynb`.

---

### Why use notebooks?

- **Learn step by step** — Run one cell at a time instead of a whole script, so you can see what each part does and fix things as you go. Great for learning, as you can clearly see the effect of each action.

- **Good for large data** — You can run a subset of cells instead of the whole file (unlike a regular script). Once you load a large dataset in one cell, it stays in memory, so other cells can use it without reloading every time.

- **Experiment safely** — Change a cell and re-run just that cell to try ideas without re-running everything.

- **Visualise the process step by step** — Each cell produces its own output, so you can see the result of every change (e.g. after loading data, after filtering, after aggregating). A script, by contrast, typically has one input and one final output, so the steps in between are hidden.

---

### Using notebooks

#### Adding a cell

- **Add Code** — Top bar, or hover above/below a cell to insert a new cell.

#### Running cells

- **Current cell** — Press the **Play** triangle on the left of the cell.  
  Keeps the state of all previously run cells and **variables** (the names that hold your data and results).

- **All cells** — **Run All** in the top bar.  
  Runs every cell in order and redefines all variables.

- **All above** — **Play** with up arrow (top-right of cell).  
  Runs all cells above the current one; resets variables defined before this cell.

- **Current and below** — **Play** with down arrow (top-right of cell).  
  Runs from the current cell onwards.

- **Restart** — Top bar. Use if you see odd behaviour or bugs; clears the notebook’s memory.

---

### Viewing data
If the last line of a cell is simply a variable name, this is what will be displayed below

## What is pandas?

**pandas** is a Python library for working with tabular data — the kind you’d see in a spreadsheet or a CSV file. It gives you structures and tools to load, filter, summarise, and transform data without writing lots of manual loops.

- **DataFrames** — The main object you'll use: a table with rows and columns (and column names) for holding and processing the data. Most of your work in this notebook will be with DataFrames.

**Documentation:** [pandas user guide](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)

In the next cells we’ll use pandas to load and explore the sample transfer data.

In [2]:
import pandas as pd # Import pandas library

# These are common options I use, to display all data (avoiding truncation)
pd.set_option('display.max_columns', None) # Display all columns
pd.set_option('display.max_colwidth', None) # Display full width of each column

## Loading data

Pandas can read from CSV, Excel, and other file types. The result is a **DataFrame**. Run the cell below to load the sample transfer data (and optionally from Excel if you have the file). The variable name you assign (e.g. `data_from_csv`) is what you'll use in later cells.

In [3]:
# Read data from files

# Read from csv
data_from_csv = pd.read_csv('sample_transfers.csv')

# Read from excel
data_from_excel = pd.read_excel('sample_transfers.xlsx')

#NOTE: If multiple sheets in Excel, can specify via sheet_name argument (default is first sheet)
# data_from_excel_sheet_2 = pd.read_excel('sample_transfers.xlsx', sheet_name=sheet_2)

data_from_csv

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
1,1344aab40ce54f218b31b2e9ffc8e7f3,1725299402000,2024-09-02 17:50:02.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,withdrawal,349999.00000,USDT,TRON,binance,1,trx,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
2,232076446.0,1725299442000,2024-09-02 17:50:42.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,deposit,349999.00000,USDT,TRON,okx,1,usdt-trc20,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
4,227821423.0,1725313303000,2024-09-02 21:41:43.000,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,0x0f9ffc720FD3D7a1303C54BfD29d6aa5960D0790,withdrawal,8333.33000,USDC,POLYGON,okx,1,usdc-polygon,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,True,USDC,usd-coin,1.000325,8336.042486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13036,335254169.0,1756592450000,2025-08-30 22:20:50.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,withdrawal,149997.70000,USDT,TRON,okx,1,usdt-trc20,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13037,200156342.0,1756592596000,2025-08-30 22:23:16.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,deposit,149997.70000,USDT,TRON,bybit,1,trx,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13038,NaN,1756653671000,2025-08-31 15:21:11.000,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,True,USDC,usd-coin,0.999801,0.000010
13039,NaN,1756657679000,2025-08-31 16:27:59.000,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00150,USDC,ETHEREUM,evm,1,ethereum,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,True,USDC,usd-coin,0.999801,0.001500
13040,NaN,1756684619000,2025-08-31 23:56:59.000,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,True,USDC,usd-coin,0.999801,0.000010

## Saving data

In [ ]:
# Save to csv
data_from_csv.to_csv('data_from_csv.csv', index=False)

# Save to excel
data_from_csv.to_excel('data_from_csv.xlsx', index=False)

## Useful functionality

Once you have a DataFrame loaded, these are some of the most useful ways to inspect it: size, column names, and a peek at the data.

In [4]:
# Number of rows
len(data_from_csv)

13041

In [5]:
# Column names
data_from_csv.columns

Index(['id', 'timestamp', 'datetime', 'txid', 'address', 'type', 'amount',
       'currency', 'network', 'exchange', 'account', 'network_original',
       'txid_original', 'txid_standardised', 'currency_original',
       'coingecko_id', 'usd_price', 'usd_value'],
      dtype='object')

In [6]:
# View first x rows (default x = 5)
x=3
data_from_csv.head(x)

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
1,1344aab40ce54f218b31b2e9ffc8e7f3,1725299402000,2024-09-02 17:50:02.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,withdrawal,349999.00000,USDT,TRON,binance,1,trx,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
2,232076446.0,1725299442000,2024-09-02 17:50:42.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,deposit,349999.00000,USDT,TRON,okx,1,usdt-trc20,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235

In [7]:
# View last x rows (default x = 5)
data_from_csv.tail(x)

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
13038,NaN,1756653671000,2025-08-31 15:21:11.000,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,True,USDC,usd-coin,0.999801,0.00001
13039,NaN,1756657679000,2025-08-31 16:27:59.000,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00150,USDC,ETHEREUM,evm,1,ethereum,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,True,USDC,usd-coin,0.999801,0.00150
13040,NaN,1756684619000,2025-08-31 23:56:59.000,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,True,USDC,usd-coin,0.999801,0.00001

In [8]:
# Sorting by column (ascending = True by default)
timestamp_ascending = data_from_csv.sort_values(by='timestamp')
timestamp_ascending

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
1,1344aab40ce54f218b31b2e9ffc8e7f3,1725299402000,2024-09-02 17:50:02.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,withdrawal,349999.00000,USDT,TRON,binance,1,trx,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
2,232076446.0,1725299442000,2024-09-02 17:50:42.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,deposit,349999.00000,USDT,TRON,okx,1,usdt-trc20,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
4,227821423.0,1725313303000,2024-09-02 21:41:43.000,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,0x0f9ffc720FD3D7a1303C54BfD29d6aa5960D0790,withdrawal,8333.33000,USDC,POLYGON,okx,1,usdc-polygon,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,True,USDC,usd-coin,1.000325,8336.042486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13036,335254169.0,1756592450000,2025-08-30 22:20:50.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,withdrawal,149997.70000,USDT,TRON,okx,1,usdt-trc20,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13037,200156342.0,1756592596000,2025-08-30 22:23:16.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,deposit,149997.70000,USDT,TRON,bybit,1,trx,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13038,NaN,1756653671000,2025-08-31 15:21:11.000,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,True,USDC,usd-coin,0.999801,0.000010
13039,NaN,1756657679000,2025-08-31 16:27:59.000,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00150,USDC,ETHEREUM,evm,1,ethereum,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,True,USDC,usd-coin,0.999801,0.001500
13040,NaN,1756684619000,2025-08-31 23:56:59.000,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,True,USDC,usd-coin,0.999801,0.000010

In [9]:
timestamp_descending = data_from_csv.sort_values(by='timestamp', ascending=False)
timestamp_descending

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
13040,NaN,1756684619000,2025-08-31 23:56:59.000,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,True,USDC,usd-coin,0.999801,0.000010
13039,NaN,1756657679000,2025-08-31 16:27:59.000,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00150,USDC,ETHEREUM,evm,1,ethereum,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,True,USDC,usd-coin,0.999801,0.001500
13038,NaN,1756653671000,2025-08-31 15:21:11.000,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,True,USDC,usd-coin,0.999801,0.000010
13037,200156342.0,1756592596000,2025-08-30 22:23:16.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,deposit,149997.70000,USDT,TRON,bybit,1,trx,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13036,335254169.0,1756592450000,2025-08-30 22:20:50.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,withdrawal,149997.70000,USDT,TRON,okx,1,usdt-trc20,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,227821423.0,1725313303000,2024-09-02 21:41:43.000,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,0x0f9ffc720FD3D7a1303C54BfD29d6aa5960D0790,withdrawal,8333.33000,USDC,POLYGON,okx,1,usdc-polygon,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,True,USDC,usd-coin,1.000325,8336.042486
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
2,232076446.0,1725299442000,2024-09-02 17:50:42.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,deposit,349999.00000,USDT,TRON,okx,1,usdt-trc20,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
1,1344aab40ce54f218b31b2e9ffc8e7f3,1725299402000,2024-09-02 17:50:02.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,withdrawal,349999.00000,USDT,TRON,binance,1,trx,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305

In [10]:
# Sorting by multiple columns (sorts by value 1, any equalities are sorted by value 2)
data_from_csv.sort_values(by=['timestamp', 'amount'])

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
1,1344aab40ce54f218b31b2e9ffc8e7f3,1725299402000,2024-09-02 17:50:02.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,withdrawal,349999.00000,USDT,TRON,binance,1,trx,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
2,232076446.0,1725299442000,2024-09-02 17:50:42.000,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,TYtjLQbGWE19Qc1aKM5ARmRCNS2gkq77mR,deposit,349999.00000,USDT,TRON,okx,1,usdt-trc20,a068d9ab4783095b904b6d092859d70cc4e02845fecb0c1808344d757fe0da89,True,USDT,tether,1.000525,350182.735235
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
4,227821423.0,1725313303000,2024-09-02 21:41:43.000,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,0x0f9ffc720FD3D7a1303C54BfD29d6aa5960D0790,withdrawal,8333.33000,USDC,POLYGON,okx,1,usdc-polygon,0x80170d111aadbb32d3c55d4b98088fc2593e8809b60198161881f0a82f3e0034,True,USDC,usd-coin,1.000325,8336.042486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13036,335254169.0,1756592450000,2025-08-30 22:20:50.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,withdrawal,149997.70000,USDT,TRON,okx,1,usdt-trc20,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13037,200156342.0,1756592596000,2025-08-30 22:23:16.000,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,TNEpbAdnM3esme1ML4YDmB8r3kcWXLgXuM,deposit,149997.70000,USDT,TRON,bybit,1,trx,35243c8bc376ef4dac73d34ac2524778b1b9d47b8f75e5c915398424126c247b,True,USDT,tether,1.000218,150030.413290
13038,NaN,1756653671000,2025-08-31 15:21:11.000,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0x92fe3a4c7140517a64498a95cfaf19679cbf11491ca0a88a42ef3d258b453770,True,USDC,usd-coin,0.999801,0.000010
13039,NaN,1756657679000,2025-08-31 16:27:59.000,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00150,USDC,ETHEREUM,evm,1,ethereum,0xdb2c3d788d92f60f92f235c1c92b64ac2ef0e22310f600db8e2db1011797caec,True,USDC,usd-coin,0.999801,0.001500
13040,NaN,1756684619000,2025-08-31 23:56:59.000,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854,deposit,0.00001,USDC,ETHEREUM,evm,1,ethereum,0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df,True,USDC,usd-coin,0.999801,0.000010

In [11]:
# Unique values in a column
data_from_csv['currency'].unique()

array(['BTC', 'USDT', 'USDC', 'SOL', 'TON', 'ETH', 'DOGE', 'JLP', 'TRX',
       'TIA', 'PEOPLE', 'SUI', 'APE', 'DOGS', 'PNUT', 'APT', 'XRP', 'ADA',
       'WIF', 'XLM', 'PEPE', 'HBAR', 'TRB', 'BCH', 'TRUMP', 'MELANIA',
       'JUP', 'ACT', 'LTC', 'WLD', 'KAITO'], dtype=object)

In [12]:
# Number of occurrences of each value in a column
data_from_csv['currency'].value_counts()

currency
USDC       3279
JLP        3146
USDT       1889
BTC        1563
ETH        1168
SOL         475
XRP         426
DOGE        423
PEPE        166
TRUMP       135
SUI          99
LTC          43
ADA          38
HBAR         36
WIF          30
PNUT         29
XLM          14
TRX          12
WLD          10
KAITO        10
TIA          10
TON          10
MELANIA       6
DOGS          4
APE           4
TRB           4
ACT           4
BCH           2
PEOPLE        2
JUP           2
APT           2
Name: count, dtype: int64

In [13]:
# Minimum column value
data_from_csv['datetime'].min()

'2024-09-02 17:47:11.000'

In [20]:
data_from_csv['datetime'].max()

'2025-08-31 23:56:59.000'

In [15]:
# Combining DataFrames
combined = pd.concat([data_from_csv, data_from_excel])

## Data Selection

### Indexing

In [16]:
# By index (iloc)
# First row
data_from_csv.iloc[0]
# First 3 rows
data_from_csv.iloc[:3]
# Last row
data_from_csv.iloc[-1]

id                                                                                  NaN
timestamp                                                                 1756684619000
datetime                                                        2025-08-31 23:56:59.000
txid                 0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df
address                                      0xb36de934a9f4bcd6770c4bf633f9afa69f8b5854
type                                                                            deposit
amount                                                                          0.00001
currency                                                                           USDC
network                                                                        ETHEREUM
exchange                                                                            evm
account                                                                               1
network_original                                                               ethereum
txid_original        0xf690e5405ffd768c4a2b4b83a1b096e10d58399037507d7f484d0a632aa4f1df
txid_standardised                                                                  True
currency_original                                                                  USDC
coingecko_id                                                                   usd-coin
usd_price                                                                      0.999801
usd_value                                                                       0.00001
Name: 13040, dtype: object

### Filtering

Use square brackets with a **condition** inside: you get back all rows where the condition is true.

- **Single condition** — e.g. keep rows where `currency` equals `'BTC'`:
  ```python
  data_from_csv[data_from_csv['currency'] == 'BTC']
  ```

- **Multiple conditions** — Wrap each condition in parentheses and join with `&` (and) or `|` (or).  
  Example: `(data_from_csv['currency'] == 'BTC') | (data_from_csv['currency'] == 'ETH')`

The cells below show filtering by one value and by a list of values (`.isin()`).

In [17]:
# Equal to value
btc_rows = data_from_csv[data_from_csv['currency'] == 'BTC']
btc_rows

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
5,227823064.0,1725314647000,2024-09-02 22:04:07.000,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,9.99998,BTC,BITCOIN,okx,1,btc-bitcoin,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,True,BTC,bitcoin,57357.716173,573576.014574
6,NaN,1725314829000,2024-09-02 22:07:09.000,a05a6beb3559da4372bb59af3700810d7c4d123ec5d0904202f37b895d441d06,15TvDTngZpD2G7frcgxoiHC3qsvmYw4Sfz,withdrawal,4.49990,BTC,BITCOIN,phemex,1,bitcoin,a05a6beb3559da4372bb59af3700810d7c4d123ec5d0904202f37b895d441d06,True,BTC,bitcoin,57357.716173,258103.987006
7,4149957489796442371,1725315142000,2024-09-02 22:12:22.000,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,9.99998,BTC,BITCOIN,binance,1,btc,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,True,BTC,bitcoin,57357.716173,573576.014574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13015,199846098.0,1756476657000,2025-08-29 14:10:57.000,07cd6d9fe46e4c6da2535bf1c6bb915a95ffcf0d7dcd81d7e07eba4cb7230fb3,15TvDTngZpD2G7frcgxoiHC3qsvmYw4Sfz,deposit,2.99960,BTC,BITCOIN,bybit,1,btc,07cd6d9fe46e4c6da2535bf1c6bb915a95ffcf0d7dcd81d7e07eba4cb7230fb3,True,BTC,bitcoin,112525.597407,337531.781981
13020,DB:82b960b684ca47df540f3e0426a42299f1f5435f01ad8dca68c86e581dd51e95,1756478339000,2025-08-29 14:38:59.000,d1940b892d9d5e8c7f46b33e5328d4aaa4f567ac8e0cd3a91ba39766ade3279d,3C5CArBaBMc1Wa74Fs3toTUVKrBezr1MLS,withdrawal,1.79994,BTC,BITCOIN,bullish,1,btc,d1940b892d9d5e8c7f46b33e5328d4aaa4f567ac8e0cd3a91ba39766ade3279d,True,BTC,bitcoin,112525.597407,202539.323796
13021,334073118.0,1756478691000,2025-08-29 14:44:51.000,d1940b892d9d5e8c7f46b33e5328d4aaa4f567ac8e0cd3a91ba39766ade3279d,3C5CArBaBMc1Wa74Fs3toTUVKrBezr1MLS,deposit,1.79994,BTC,BITCOIN,okx,1,btc-bitcoin,d1940b892d9d5e8c7f46b33e5328d4aaa4f567ac8e0cd3a91ba39766ade3279d,True,BTC,bitcoin,112525.597407,202539.323796
13028,7405583,1756508914000,2025-08-29 23:08:34.000,ced1c271b3f1925582e9ad942ace865074a54cf7d5fa468b0e5e5ae4855401f4,15TvDTngZpD2G7frcgxoiHC3qsvmYw4Sfz,withdrawal,2.99960,BTC,BITCOIN,cryptocom,1,btc,ced1c271b3f1925582e9ad942ace865074a54cf7d5fa468b0e5e5ae4855401f4/0,True,BTC,bitcoin,112525.597407,337531.781981
13029,199953575.0,1756510324000,2025-08-29 23:32:04.000,ced1c271b3f1925582e9ad942ace865074a54cf7d5fa468b0e5e5ae4855401f4,15TvDTngZpD2G7frcgxoiHC3qsvmYw4Sfz,deposit,2.99960,BTC,BITCOIN,bybit,1,btc,ced1c271b3f1925582e9ad942ace865074a54cf7d5fa468b0e5e5ae4855401f4,True,BTC,bitcoin,112525.597407,337531.781981

In [18]:
# In a list of values
btc_or_eth_rows = data_from_csv[data_from_csv['currency'].isin(['BTC', 'ETH'])]

# Note this is equal to
data_from_csv[(data_from_csv['currency'] == 'BTC') | (data_from_csv['currency'] == 'ETH')]

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
0,227794235.0,1725299231000,2024-09-02 17:47:11.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,5.99997,BTC,BITCOIN,okx,1,btc-bitcoin,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
5,227823064.0,1725314647000,2024-09-02 22:04:07.000,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,withdrawal,9.99998,BTC,BITCOIN,okx,1,btc-bitcoin,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,True,BTC,bitcoin,57357.716173,573576.014574
6,NaN,1725314829000,2024-09-02 22:07:09.000,a05a6beb3559da4372bb59af3700810d7c4d123ec5d0904202f37b895d441d06,15TvDTngZpD2G7frcgxoiHC3qsvmYw4Sfz,withdrawal,4.49990,BTC,BITCOIN,phemex,1,bitcoin,a05a6beb3559da4372bb59af3700810d7c4d123ec5d0904202f37b895d441d06,True,BTC,bitcoin,57357.716173,258103.987006
7,4149957489796442371,1725315142000,2024-09-02 22:12:22.000,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,9.99998,BTC,BITCOIN,binance,1,btc,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,True,BTC,bitcoin,57357.716173,573576.014574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13029,199953575.0,1756510324000,2025-08-29 23:32:04.000,ced1c271b3f1925582e9ad942ace865074a54cf7d5fa468b0e5e5ae4855401f4,15TvDTngZpD2G7frcgxoiHC3qsvmYw4Sfz,deposit,2.99960,BTC,BITCOIN,bybit,1,btc,ced1c271b3f1925582e9ad942ace865074a54cf7d5fa468b0e5e5ae4855401f4,True,BTC,bitcoin,112525.597407,337531.781981
13030,167511643.0,1756510622000,2025-08-29 23:37:02.000,0xe5f73ece20ae8001ec2c4dde26eca459f9bb1b4d486ffa552c67cc4ef9e97e15,0xbD89De0CDbF52Aa77b6d3b662CD08BD6ad5f3e4C,withdrawal,74.99950,ETH,ETHEREUM,bybit,1,eth,0xe5f73ece20ae8001ec2c4dde26eca459f9bb1b4d486ffa552c67cc4ef9e97e15,True,ETH,ethereum,4507.560431,338064.778547
13031,8713482,1756510712000,2025-08-29 23:38:32.000,0xe5f73ece20ae8001ec2c4dde26eca459f9bb1b4d486ffa552c67cc4ef9e97e15,0xbD89De0CDbF52Aa77b6d3b662CD08BD6ad5f3e4C,deposit,74.99950,ETH,ETHEREUM,cryptocom,1,NaN,0xe5f73ece20ae8001ec2c4dde26eca459f9bb1b4d486ffa552c67cc4ef9e97e15/0,True,ETH,ethereum,4507.560431,338064.778547
13034,167699464.0,1756592320000,2025-08-30 22:18:40.000,0xb5f0e271730eba3fc6227c269e676e83dd7363815a6c497d26765ee234e5089c,0xbD89De0CDbF52Aa77b6d3b662CD08BD6ad5f3e4C,withdrawal,49.99950,ETH,ETHEREUM,bybit,1,eth,0xb5f0e271730eba3fc6227c269e676e83dd7363815a6c497d26765ee234e5089c,True,ETH,ethereum,4364.358521,218215.743892
13035,8717894,1756592396000,2025-08-30 22:19:56.000,0xb5f0e271730eba3fc6227c269e676e83dd7363815a6c497d26765ee234e5089c,0xbD89De0CDbF52Aa77b6d3b662CD08BD6ad5f3e4C,deposit,49.99950,ETH,ETHEREUM,cryptocom,1,NaN,0xb5f0e271730eba3fc6227c269e676e83dd7363815a6c497d26765ee234e5089c/0,True,ETH,ethereum,4364.358521,218215.743892

In [19]:
# Negation
# Use ~ to negate a condition (or regular comparative operator)

non_binance_rows = data_from_csv[data_from_csv['exchange'] != 'binance']

non_binance_rows = data_from_csv[~(data_from_csv['exchange'] == 'binance')]

## Examples

### Number of deposits to Binance in September 2024

In [22]:
binance_sep_24_deposits = data_from_csv[
    (data_from_csv['exchange'] == 'binance') &
    (data_from_csv['type'] == 'deposit') &
    (data_from_csv['datetime'] >= '2024-09-01') &
    (data_from_csv['datetime'] <= '2024-09-30')
]

binance_sep_24_deposits_count = len(binance_sep_24_deposits)
print(f"Number of deposits to Binance in September 2024: {binance_sep_24_deposits_count}")
binance_sep_24_deposits

Number of deposits to Binance in September 2024: 7

,id,timestamp,datetime,txid,address,type,amount,currency,network,exchange,account,network_original,txid_original,txid_standardised,currency_original,coingecko_id,usd_price,usd_value
3,4149709874429290753,1725300383000,2024-09-02 18:06:23.000,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,5.99997,BTC,BITCOIN,binance,1,btc,7f58b6412d1d3cfecddafa07569010f66574e80e7dea6008cff6c8acdc49685f,True,BTC,bitcoin,57357.716173,344144.576305
7,4149957489796442371,1725315142000,2024-09-02 22:12:22.000,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,1MS2F8kiM7JHctQcgxMUxrmUPizDkoWMg6,deposit,9.99998,BTC,BITCOIN,binance,1,btc,be30cd43f00319f8f57bd7717ff4d7bd7f10841dc2fe334c084771cffb4e8cd0,True,BTC,bitcoin,57357.716173,573576.014574
19,4153835449406273537,1725546286000,2024-09-05 14:24:46.000,cb720f7507992d738979cf14238b943262d8547a018278176fc8e247da2b8270,TNGYzyUv4NoYHHdone9vhD27mXhN2uW9Ms,deposit,299998.70000,USDT,TRON,binance,1,trx,cb720f7507992d738979cf14238b943262d8547a018278176fc8e247da2b8270,True,USDT,tether,1.000062,300017.246883
23,4155373341047855616,1725637952000,2024-09-06 15:52:32.000,0x6582c247274e13cd658fde8f9e8422538f3fecf12a70b72c998fb53757c9fade,0x9f02af3313fe66e3cc90319701b6c512e144b857,deposit,349996.97000,USDC,ETHEREUM,binance,1,eth,0x6582c247274e13cd658fde8f9e8422538f3fecf12a70b72c998fb53757c9fade,True,USDC,usd-coin,1.000095,350030.150967
27,4155783683699718145,1725662410000,2024-09-06 22:40:10.000,f3a12afa1ab68abb25db2868f3f9fa6fc9fd2a92243d6fd0a48e7435967813b6,TNGYzyUv4NoYHHdone9vhD27mXhN2uW9Ms,deposit,349999.00000,USDT,TRON,binance,1,trx,f3a12afa1ab68abb25db2868f3f9fa6fc9fd2a92243d6fd0a48e7435967813b6,True,USDT,tether,0.999541,349838.457515
34,4160013523755808769,1725914528000,2024-09-09 20:42:08.000,9eb586eb4a2489334094f797b59551601d938646a3ce6ad676eb6b935773b295,TNGYzyUv4NoYHHdone9vhD27mXhN2uW9Ms,deposit,279998.70000,USDT,TRON,binance,1,trx,9eb586eb4a2489334094f797b59551601d938646a3ce6ad676eb6b935773b295,True,USDT,tether,0.999248,279788.015496
48,4180017065266585089,1727106832000,2024-09-23 15:53:52.000,9b296a67a5e1813c8c43a43cc831cbd3ff00a266d4cfcd2670c9bc497d6e6103,TNGYzyUv4NoYHHdone9vhD27mXhN2uW9Ms,deposit,349999.00000,USDT,TRON,binance,1,trx,9b296a67a5e1813c8c43a43cc831cbd3ff00a266d4cfcd2670c9bc497d6e6103,True,USDT,tether,1.000260,350089.924185

### Total amount of ETH withdrawn from Binance, Okx, Bybit

In [24]:
eth_withdrawals_from_binance_okx_bybit = data_from_csv[
    (data_from_csv['exchange'].isin(['binance', 'okx', 'bybit'])) &
    (data_from_csv['currency'] == 'ETH') &
    (data_from_csv['type'] == 'withdrawal')
]

total_eth_amount = eth_withdrawals_from_binance_okx_bybit['amount'].sum()

print(f"Total amount of ETH withdrawn from Binance, Okx, Bybit: {total_eth_amount}")

Total amount of ETH withdrawn from Binance, Okx, Bybit: 52213.80593911999